### PR TITLE
Compatibility with Django 3

### PR DESCRIPTION
**Pull request by xavier-lr**
Context removed since Django 3

Subject: Avoid errors of missing argument 'context'

### Feature or Bugfix
- Bugfix

### Purpose
- Avoid following error on Django 3:
`convert_uuidfield_value() missing 1 required positional argument: 'context'
`

### Detail
- You can reproduce the issue setting UUID field on Django 3, saving the object and then loading it again.

### Relates
- None

### CODE REVIEW

**Comment by shimizukawa** [comment]
Thanks!

I checked the history of this problem to validate the fix.
First, the `convert_uuidfield_value` was introduced in PR #24, around the time of Django-1.11. Postgres supports the uuid type, but [Redshift treats it as a string](https://docs.aws.amazon.com/redshift/latest/dg/federated-data-types.html). This django-redshift-backend is based on the postgres backend, so it doesn't have uuid support. I guess the PR #24 is based on MySQL's uuid support code: https://github.com/django/django/blob/1.11/django/db/backends/mysql/operations.py#L242-L245

At the same time, the `context` argument was removed from Django itself on https://github.com/django/django/pull/8709 then this fix is reflected in Django 2.0. This means that anyone using the uuid type in django-redshift-backend after Django 2.0 was affected (I was not using the uuid type).

Thanks for the nice fix!

File: django_redshift_backend/base.py [hunk 1]
```diff
@@ -87,7 +87,8 @@ def get_db_converters(self, expression):
             converters.append(self.convert_uuidfield_value)
         return converters
 
-    def convert_uuidfield_value(self, value, expression, connection, context):
+    def convert_uuidfield_value(self, value, expression, connection,
+                                context=None):
```
Comment (shimizukawa) [inline django_redshift_backend/base.py:91]: Please remove `context` argument completely because `context` has been removed since django 2.0 and django-redshift-backend already drop support django 1.x.

**Review by shimizukawa — CHANGES_REQUESTED** [review]

**Review by shimizukawa — APPROVED** [review]
LGTM!

File: django_redshift_backend/base.py (hunk 1 above)
Comment (xavier-lr) [reply django_redshift_backend/base.py]: context removed !

**Comment by shimizukawa** [comment]
I'm going to release 2.1.0 in this week.

**Comment by shimizukawa** [comment]
Released! https://pypi.org/project/django-redshift-backend/2.1.0/
